### ISSUE TITLE
linux-exfat-oot vs exfat-linux?

### ISSUE THREAD

**Issue by tmm1** [namjaejeon/linux-exfat-oot#16]
Hi, I am trying to understand how this driver is related to https://github.com/arter97/exfat-linux ?

**Comment by tmm1** [comment]
@namjaejeon can you provide any guidance?

**Comment by namjaejeon** [comment]
Both drivers is created with same purpose. i.e. the latest exfat driver on low version kernel version can be used.
So you need to choose the one after checking maintenance status of both drivers.
