### ISSUE TITLE
exfat disk usage of large file misreported

### ISSUE THREAD

**Issue by hgkamath** [namjaejeon/linux-exfat-oot#30]
A large file in the exfat partition shows a very small disk-usage. This may be easy bug to fix. Seems like a 64bit number is truncated to lower 32bits in disk usage reporting. 

https://bugzilla.kernel.org/show_bug.cgi?id=214701

https://gitlab.gnome.org/GNOME/baobab/-/issues/58

sorry for duplicate bug filing. I just did not know where the right place to file the bug was. 

If you can't reproduce it yourself, let me know how to troubleshoot the file on my system which misreports its disk-usage to get the information needed.

**Comment by namjaejeon** [comment]
I have applied the patch to #master.
Please close this issue.

**Comment by hgkamath** [comment]
Link to kernel commit : 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs?id=9c6e8d52a7299b1596334ca49171f2efedc15ef6 

Resolved
