### ISSUE TITLE
Write failure when using fdatasync on linux-4.4

### ISSUE THREAD

**Issue by kuehnelth** [namjaejeon/linux-exfat-oot#34]
I was debugging an issue when using exfat on a linux 4.4 based system where write calls on a exfat partition returned -EIO.
I can reproduce it with the following short C program. https://gist.github.com/kuehnelth/5f217bd96efef09d4f2841de32b3ef06

After running the program the kernel prints
```
exFAT-fs (ubda): error, failed to bmap (inode : 000000007041b0a8 iblock : 0, err : -5)
exFAT-fs (ubda): Filesystem has been set read-only
```
After remounting both test files are gone so the fdatasyc doesn't seem to cause the new directory entries to be written to disk.
Without the fdatasync the program runs fine. On linux-4.9 it also works with fdatasync.

**Comment by namjaejeon** [comment]
When I have tested your testcode on linux 5.18, there is no issue. This issue is only caused on linux 4.4 ?

**Comment by kuehnelth** [comment]
Yes, the issue only happens on linux 4.4. On linux 4.9 or newer I can't reproduce it. (I haven't tested versions from 4.5 to 4.8)

**Comment by kuehnelth** [comment]
I did a git bisect on the kernel today to find out when the problem stops showing up and arrived at the following commit.
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=2a222ca992c35aee1e83af428f3dd26a3f5d5d94
This is the first commit that doesn't show the issue. Going 1 commit back the issue is visible again.

I also think I found a fix for the issue. I changed the `write_dirty_buffer` call in `exfat_update_bhs` to `write_dirty_buffer(bhs[i], WRITE_SYNC);`. On newer kernel versions `REQ_SYNC` seems to bee enough.

The `__sync_dirty_buffer` call in `exfat_set_vol_flags` maybe also has to be changed on pre 4.8. But I'm not sure about that.

**Comment by namjaejeon** [comment]
Thanks for your check and changes. I have applied the patch(https://github.com/namjaejeon/linux-exfat-oot/commit/fa4f895f67ce805163603d0cbf684df71319c303) to fix this issue. Please check it.

> Do you plan to create new tags and releases here on github or do you just consider the master branch to be stable?

master branch is stable version. Let me know if you have any issue.

**Comment by kuehnelth** [comment]
With the current master it looks fine. Thanks.

**Comment by namjaejeon** [comment]
Thank you too!
