### ISSUE TITLE
delete large size files will stuck when SSD enable trim

### ISSUE THREAD

**Issue by jh5254622** [namjaejeon/linux-exfat-oot#36]
When SSD enable trim(mount with discard),delete large size files will stuck.
The reason is sb_issue_discard cost long time in exfat_clear_bitmap.

**Comment by namjaejeon** [comment]
Ah, Could you please elaborate more why it is exfat issue ? There is no issue with ext4(w discard option) ?

**Comment by namjaejeon** [comment]
ext4 is also calling sb_issue_discard() with discard option.

**Comment by jh5254622** [comment]
yes,ext4 have same problem,may NG.
