### ISSUE TITLE
Exfat filesystem broken will case other files lost

### ISSUE THREAD

**Issue by jh5254622** [namjaejeon/linux-exfat-oot#39]
(1). format the disk(SSD) on PC(win7);
(2). upload some files to the disk in directory A and umount from PC;
(3). mount the disk by linux-exfat-oot on arm device; 
(4). upload files to disk on arm device to the directory A and poweroff when uploading not finished.
some files uploaded in step (2) will be lost when the arm device reboot and mount the disk by linux-exfat-oot.

**Comment by jh5254622** [comment]
the files is lost when remount by linux-exfat-oot.

**Comment by namjaejeon** [comment]
What files are you lost ? copied file from step(2) ? or step(4) ?

**Comment by jh5254622** [comment]
> 

step(2)

**Comment by jh5254622** [comment]
The bug may case by the trim function of the SSD
sorry,I will close this issue.
