### ISSUE TITLE
cannot copy files( few mbs) to SSD 

### ISSUE THREAD

**Issue by i928** [namjaejeon/linux-exfat-oot#48]
namjaejeon,
Thanks for your work. I test read/write on memory stick. It works properly.
For 245G SSD, it can copy small files(few k) from SSD to internal SD, and copy small files from internal SD to SSD. It does not work for file size greater than few mb.
my phone is Pixel 3XL on lineage 20 with kernel 4.9.337 version.

**Comment by namjaejeon** [comment]
Your issue is clear ?

**Comment by i928** [comment]
Yes, Thanks! It is pixel3xl kernel issues, not related to filesystems.
    On Thursday, May 4, 2023 at 04:58:10 PM PDT, Namjae Jeon ***@***.***> wrote:  
 
 


Your issue is clear ?
